{% set name = "llmtuner" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hiyouga/LLaMA-Factory/archive/v{{ version }}.tar.gz
  sha256: 214799de46778a5163084124fcf0d82b1b7702439b8c541f5800d2ba8dfb6ebe

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - pip
  run:
    - python >=3.8
    - pytorch >=1.13.1
    - transformers >=4.37.2
    - datasets >=2.14.3
    - accelerate >=0.27.2
    - peft >=0.10.0
    - trl >=0.8.1
    - gradio <4.0.0,>=3.38.0
    - scipy
    - einops
    - sentencepiece
    - protobuf
    - uvicorn
    - pydantic
    - fastapi
    - sse-starlette
    - matplotlib-base
    - fire
    - galore-torch

test:
  imports:
    - llmtuner
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hiyouga/LLaMA-Factory
  summary: Easy-to-use LLM fine-tuning framework
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
